# AI Fundamental Stock Analysis

In [ ]:
import yfinance as yf
import pandas as pd

Select Microsoft (MSFT is Microsofts ticker symbol)

In [ ]:
ticker = yf.Ticker("MSFT")

Financial Statements

In [63]:
income_statement = ticker.income_stmt
income_statement

,2026-06-30,2025-06-30,2024-06-30,2023-06-30
Tax Effect Of Unusual Items,1.110650e+09,-7.721784e+07,-1.000900e+08,-2.850000e+06
Tax Rate For Calcs,1.940000e-01,1.762960e-01,1.823130e-01,1.900000e-01
Normalized EBITDA,2.017940e+11,1.558830e+11,1.322290e+11,1.051550e+11
Total Unusual Items,5.725000e+09,-4.380000e+08,-5.490000e+08,-1.500000e+07
Total Unusual Items Excluding Goodwill,5.725000e+09,-4.380000e+08,-5.490000e+08,-1.500000e+07
Net Income From Continuing Operation Net Minority Interest,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Reconciled Depreciation,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10
Reconciled Cost Of Revenue,1.063740e+11,8.783100e+10,7.411400e+10,6.586300e+10
EBITDA,2.075190e+11,1.554450e+11,1.316800e+11,1.051400e+11
EBIT,1.689850e+11,1.260120e+11,1.107220e+11,9.127900e+10
Net Interest Income,2.500000e+08,2.620000e+08,2.220000e+08,1.026000e+09
Interest Expense,3.051000e+09,2.385000e+09,2.935000e+09,1.968000e+09
Interest Income,3.301000e+09,2.647000e+09,3.157000e+09,2.994000e+09
Normalized Income,1.291346e+11,1.021928e+11,8.858491e+10,7.237315e+10
Net Income From Continuing And Discontinued Operation,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Total Expenses,1.766020e+11,1.531960e+11,1.356890e+11,1.233920e+11
Total Operating Income As Reported,1.552370e+11,1.285280e+11,1.094330e+11,8.852300e+10
Diluted Average Shares,7.453000e+09,7.465000e+09,7.469000e+09,7.472000e+09
Basic Average Shares,7.429000e+09,7.433000e+09,7.431000e+09,7.446000e+09
Diluted EPS,1.795000e+01,1.364000e+01,1.180000e+01,9.680000e+00
Basic EPS,1.800000e+01,1.370000e+01,1.186000e+01,9.720000e+00
Diluted NI Availto Com Stockholders,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income Common Stockholders,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income Including Noncontrolling Interests,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Net Income Continuous Operations,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10
Tax Provision,3.218500e+10,2.179500e+10,1.965100e+10,1.695000e+10
Pretax Income,1.659340e+11,1.236270e+11,1.077870e+11,8.931100e+10
Other Income Expense,1.044700e+10,-5.163000e+09,-1.868000e+09,-2.380000e+08
Other Non Operating Income Expenses,4.722000e+09,-4.725000e+09,-1.319000e+09,-2.230000e+08
Special Income Charges,-1.780000e+08,-9.430000e+08,-2.060000e+08,-3.000000e+07
Write Off,1.780000e+08,9.430000e+08,2.060000e+08,3.000000e+07
Gain On Sale Of Security,5.903000e+09,5.050000e+08,-3.430000e+08,1.500000e+07
Net Non Operating Interest Income Expense,2.500000e+08,2.620000e+08,2.220000e+08,1.026000e+09
Interest Expense Non Operating,3.051000e+09,2.385000e+09,2.935000e+09,1.968000e+09
Interest Income Non Operating,3.301000e+09,2.647000e+09,3.157000e+09,2.994000e+09
Operating Income,1.552370e+11,1.285280e+11,1.094330e+11,8.852300e+10
Operating Expense,7.022800e+10,6.536500e+10,6.157500e+10,5.752900e+10
Research And Development,3.556200e+10,3.248800e+10,2.951000e+10,2.719500e+10
Selling General And Administration,3.466600e+10,3.287700e+10,3.206500e+10,3.033400e+10
Selling And Marketing Expense,2.671000e+10,2.565400e+10,2.445600e+10,2.275900e+10
General And Administrative Expense,7.956000e+09,7.223000e+09,7.609000e+09,7.575000e+09
Other Gand A,7.956000e+09,7.223000e+09,7.609000e+09,7.575000e+09
Gross Profit,2.254650e+11,1.938930e+11,1.710080e+11,1.460520e+11
Cost Of Revenue,1.063740e+11,8.783100e+10,7.411400e+10,6.586300e+10
Total Revenue,3.318390e+11,2.817240e+11,2.451220e+11,2.119150e+11
Operating Revenue,3.318390e+11,2.817240e+11,2.451220e+11,2.119150e+11

In [64]:
balance_sheets = ticker.balance_sheet
balance_sheets

,2026-06-30,2025-06-30,2024-06-30,2023-06-30,2022-06-30
Ordinary Shares Number,7.428435e+09,7.434159e+09,7.434139e+09,7.432000e+09,NaN
Share Issued,7.428435e+09,7.434159e+09,7.434139e+09,7.432000e+09,NaN
Net Debt,1.935900e+10,1.290900e+10,3.331500e+10,1.253300e+10,NaN
Total Debt,5.682600e+10,6.058800e+10,6.712700e+10,5.996500e+10,NaN
Tangible Book Value,3.041270e+11,2.013660e+11,1.216600e+11,1.289710e+11,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,7.665100e+10,9.455500e+10,7.553100e+10,1.112560e+11,NaN
Other Short Term Investments,5.571600e+10,6.431300e+10,5.721600e+10,7.655200e+10,NaN
Cash And Cash Equivalents,2.093500e+10,3.024200e+10,1.831500e+10,3.470400e+10,NaN
Cash Equivalents,7.876000e+09,1.853100e+10,6.744000e+09,2.622600e+10,NaN
Cash Financial,1.305900e+10,1.171100e+10,1.157100e+10,8.478000e+09,NaN

In [65]:
cash_flow = ticker.cash_flow
cash_flow

,2026-06-30,2025-06-30,2024-06-30,2023-06-30,2022-06-30
Free Cash Flow,6.698700e+10,7.161100e+10,7.407100e+10,5.947500e+10,NaN
Repurchase Of Capital Stock,-2.227100e+10,-1.842000e+10,-1.725400e+10,-2.224500e+10,NaN
Repayment Of Debt,-3.000000e+09,-3.216000e+09,-2.907000e+10,-2.750000e+09,NaN
Issuance Of Debt,0.000000e+00,0.000000e+00,2.439500e+10,0.000000e+00,NaN
Issuance Of Capital Stock,2.009000e+09,2.056000e+09,2.002000e+09,1.866000e+09,NaN
Capital Expenditure,-1.159480e+11,-6.455100e+10,-4.447700e+10,-2.810700e+10,NaN
End Cash Position,2.093500e+10,3.024200e+10,1.831500e+10,3.470400e+10,NaN
Beginning Cash Position,3.024200e+10,1.831500e+10,3.470400e+10,1.393100e+10,NaN
Effect Of Exchange Rate Changes,-1.960000e+08,6.300000e+07,-2.100000e+08,-1.940000e+08,NaN
Changes In Cash,-9.111000e+09,1.186400e+10,-1.617900e+10,2.096700e+10,NaN
Financing Cash Flow,-5.254600e+10,-5.169900e+10,-3.775700e+10,-4.393500e+10,NaN
Cash Flow From Continuing Financing Activities,-5.254600e+10,-5.169900e+10,-3.775700e+10,-4.393500e+10,NaN
Net Other Financing Charges,-2.839000e+09,-2.291000e+09,-1.309000e+09,-1.006000e+09,NaN
Cash Dividends Paid,-2.644500e+10,-2.408200e+10,-2.177100e+10,-1.980000e+10,NaN
Common Stock Dividend Paid,-2.644500e+10,-2.408200e+10,-2.177100e+10,-1.980000e+10,NaN
Net Common Stock Issuance,-2.026200e+10,-1.636400e+10,-1.525200e+10,-2.037900e+10,NaN
Common Stock Payments,-2.227100e+10,-1.842000e+10,-1.725400e+10,-2.224500e+10,NaN
Common Stock Issuance,2.009000e+09,2.056000e+09,2.002000e+09,1.866000e+09,NaN
Net Issuance Payments Of Debt,-3.000000e+09,-8.962000e+09,5.750000e+08,-2.750000e+09,NaN
Net Short Term Debt Issuance,0.000000e+00,-5.746000e+09,5.250000e+09,0.000000e+00,NaN
Short Term Debt Issuance,NaN,NaN,5.250000e+09,0.000000e+00,0.0
Net Long Term Debt Issuance,-3.000000e+09,-3.216000e+09,-4.675000e+09,-2.750000e+09,NaN
Long Term Debt Payments,-3.000000e+09,-3.216000e+09,-2.907000e+10,-2.750000e+09,NaN
Long Term Debt Issuance,0.000000e+00,0.000000e+00,2.439500e+10,0.000000e+00,NaN
Investing Cash Flow,-1.395000e+11,-7.259900e+10,-9.697000e+10,-2.268000e+10,NaN
Cash Flow From Continuing Investing Activities,-1.395000e+11,-7.259900e+10,-9.697000e+10,-2.268000e+10,NaN
Net Other Investing Changes,-1.986100e+10,2.317000e+09,-1.298000e+09,-3.116000e+09,NaN
Net Investment Purchase And Sale,-1.948000e+09,-4.387000e+09,1.793700e+10,1.021300e+10,NaN
Sale Of Investment,5.640300e+10,2.538800e+10,3.566900e+10,4.786400e+10,NaN
Purchase Of Investment,-5.835100e+10,-2.977500e+10,-1.773200e+10,-3.765100e+10,NaN
Net Business Purchase And Sale,-1.743000e+09,-5.978000e+09,-6.913200e+10,-1.670000e+09,NaN
Purchase Of Business,-1.743000e+09,-5.978000e+09,-6.913200e+10,-1.670000e+09,NaN
Net PPE Purchase And Sale,-1.159480e+11,-6.455100e+10,-4.447700e+10,-2.810700e+10,NaN
Purchase Of PPE,-1.159480e+11,-6.455100e+10,-4.447700e+10,-2.810700e+10,NaN
Operating Cash Flow,1.829350e+11,1.361620e+11,1.185480e+11,8.758200e+10,NaN
Cash Flow From Continuing Operating Activities,1.829350e+11,1.361620e+11,1.185480e+11,8.758200e+10,NaN
Change In Working Capital,-4.895000e+09,-5.350000e+09,1.824000e+09,-2.388000e+09,NaN
Change In Other Working Capital,7.486000e+09,5.400000e+09,7.035000e+09,5.177000e+09,NaN
Change In Other Current Liabilities,2.140000e+09,4.947000e+09,5.616000e+09,2.825000e+09,NaN
Change In Other Current Assets,-6.591000e+09,-5.994000e+09,-8.465000e+09,-4.824000e+09,NaN
Change In Payables And Accrued Expense,5.268000e+09,5.690000e+08,3.545000e+09,-2.721000e+09,NaN
Change In Payable,5.268000e+09,5.690000e+08,3.545000e+09,-2.721000e+09,NaN
Change In Account Payable,5.268000e+09,5.690000e+08,3.545000e+09,-2.721000e+09,NaN
Change In Tax Payable,NaN,NaN,1.687000e+09,-3.580000e+08,696000000.0
Change In Income Tax Payable,NaN,NaN,1.687000e+09,-3.580000e+08,696000000.0
Change In Inventory,-4.610000e+08,3.090000e+08,1.284000e+09,1.242000e+09,NaN
Change In Receivables,-1.273700e+10,-1.058100e+10,-7.191000e+09,-4.087000e+09,NaN
Changes In Account Receivables,-1.273700e+10,-1.058100e+10,-7.191000e+09,-4.087000e+09,NaN
Stock Based Compensation,1.240500e+10,1.197400e+10,1.073400e+10,9.611000e+09,NaN
Unrealized Gain Loss On Investment Securities,NaN,-5.360000e+08,-1.460000e+08,-3.030000e+08,-509000000.0
Asset Impairment Charge,NaN,9.430000e+08,2.060000e+08,3.000000e+07,101000000.0
Deferred Tax,1.418900e+10,-7.056000e+09,-4.738000e+09,-6.059000e+09,NaN
Deferred Income Tax,1.418900e+10,-7.056000e+09,-4.738000e+09,-6.059000e+09,NaN
Depreciation Amortization Depletion,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10,NaN
Depreciation And Amortization,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10,NaN
Depreciation,3.853400e+10,2.943300e+10,2.095800e+10,1.386100e+10,NaN
Operating Gains Losses,-1.104700e+10,5.329000e+09,1.634000e+09,4.690000e+08,NaN
Gain Loss On Investment Securities,NaN,2.020000e+08,2.450000e+08,4.690000e+08,-1000000.0
Net Income From Continuing Operations,1.337490e+11,1.018320e+11,8.813600e+10,7.236100e+10,NaN

Historical Stock Prices

In [66]:
historical_data = ticker.history(period = "5y")
historical_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-10-11 00:00:00-04:00,281.123344,285.969956,280.960178,282.380585,19298600,0.0,0.0
2021-10-12 00:00:00-04:00,283.445821,283.541799,280.576246,281.084900,17974100,0.0,0.0
2021-10-13 00:00:00-04:00,283.033188,285.307737,281.670362,284.376801,23416300,0.0,0.0
2021-10-14 00:00:00-04:00,287.160021,291.056512,285.835593,290.557465,27262900,0.0,0.0
2021-10-15 00:00:00-04:00,290.163933,292.188973,288.417222,291.958618,25384800,0.0,0.0

Shapes And Null Values Check

In [67]:
print("Shape:",income_statement.shape)
print("Null values",income_statement.isna().sum())
income_statement.info()

Shape: (47, 4)
Null values 2026-06-30    0
2025-06-30    0
2024-06-30    0
2023-06-30    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, Tax Effect Of Unusual Items to Operating Revenue
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   2026-06-30 00:00:00  47 non-null     float64
 1   2025-06-30 00:00:00  47 non-null     float64
 2   2024-06-30 00:00:00  47 non-null     float64
 3   2023-06-30 00:00:00  47 non-null     float64
dtypes: float64(4)
memory usage: 2.9+ KB

In [68]:
print("Shape:",balance_sheets.shape)
print("Null values:",balance_sheets.isna().sum())
balance_sheets.info()

Shape: (79, 5)
Null values: 2026-06-30     6
2025-06-30     4
2024-06-30     1
2023-06-30     2
2022-06-30    75
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 79 entries, Ordinary Shares Number to Cash Financial
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   2026-06-30 00:00:00  73 non-null     float64
 1   2025-06-30 00:00:00  75 non-null     float64
 2   2024-06-30 00:00:00  78 non-null     float64
 3   2023-06-30 00:00:00  77 non-null     float64
 4   2022-06-30 00:00:00  4 non-null      float64
dtypes: float64(5)
memory usage: 5.8+ KB

In [69]:
print("Shape:",cash_flow.shape)
print("Null values:",cash_flow.isna().sum())
cash_flow.info()

Shape: (59, 5)
Null values: 2026-06-30     6
2025-06-30     3
2024-06-30     0
2023-06-30     0
2022-06-30    53
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 59 entries, Free Cash Flow to Net Income From Continuing Operations
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   2026-06-30 00:00:00  53 non-null     float64
 1   2025-06-30 00:00:00  56 non-null     float64
 2   2024-06-30 00:00:00  59 non-null     float64
 3   2023-06-30 00:00:00  59 non-null     float64
 4   2022-06-30 00:00:00  6 non-null      float64
dtypes: float64(5)
memory usage: 4.8+ KB

In [70]:
print("Shape:",historical_data.shape)
print("Null values:",historical_data.isna().sum())
historical_data.info()

Shape: (1254, 7)
Null values: Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1254 entries, 2021-10-11 00:00:00-04:00 to 2026-10-08 00:00:00-04:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1254 non-null   float64
 1   High          1254 non-null   float64
 2   Low           1254 non-null   float64
 3   Close         1254 non-null   float64
 4   Volume        1254 non-null   int64
 5   Dividends     1254 non-null   float64
 6   Stock Splits  1254 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 78.4 KB

### Income Statement Dataset

In [71]:
income = income_statement.copy()
income_yearly = income.T.reset_index()
income_yearly.rename(columns = {"index" :"Date"},inplace=True)
income_yearly["Date"] = pd.to_datetime(income_yearly["Date"])
income_yearly

,Date,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Total Unusual Items,Total Unusual Items Excluding Goodwill,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,...,Operating Expense,Research And Development,Selling General And Administration,Selling And Marketing Expense,General And Administrative Expense,Other Gand A,Gross Profit,Cost Of Revenue,Total Revenue,Operating Revenue
0,2026-06-30,1.110650e+09,0.194000,2.017940e+11,5.725000e+09,5.725000e+09,1.337490e+11,3.853400e+10,1.063740e+11,2.075190e+11,...,7.022800e+10,3.556200e+10,3.466600e+10,2.671000e+10,7.956000e+09,7.956000e+09,2.254650e+11,1.063740e+11,3.318390e+11,3.318390e+11
1,2025-06-30,-7.721784e+07,0.176296,1.558830e+11,-4.380000e+08,-4.380000e+08,1.018320e+11,2.943300e+10,8.783100e+10,1.554450e+11,...,6.536500e+10,3.248800e+10,3.287700e+10,2.565400e+10,7.223000e+09,7.223000e+09,1.938930e+11,8.783100e+10,2.817240e+11,2.817240e+11
2,2024-06-30,-1.000900e+08,0.182313,1.322290e+11,-5.490000e+08,-5.490000e+08,8.813600e+10,2.095800e+10,7.411400e+10,1.316800e+11,...,6.157500e+10,2.951000e+10,3.206500e+10,2.445600e+10,7.609000e+09,7.609000e+09,1.710080e+11,7.411400e+10,2.451220e+11,2.451220e+11
3,2023-06-30,-2.850000e+06,0.190000,1.051550e+11,-1.500000e+07,-1.500000e+07,7.236100e+10,1.386100e+10,6.586300e+10,1.051400e+11,...,5.752900e+10,2.719500e+10,3.033400e+10,2.275900e+10,7.575000e+09,7.575000e+09,1.460520e+11,6.586300e+10,2.119150e+11,2.119150e+11

### Balance Sheet Dataset

In [72]:
balance = balance_sheets.copy()
balance_yearly = balance.T.reset_index()
balance_yearly.rename(columns = {"index" :"Date"},inplace=True)
balance_yearly["Date"] = pd.to_datetime(balance_yearly["Date"])
balance_yearly

,Date,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Capital Lease Obligations,...,Raw Materials,Receivables,Accounts Receivable,Allowance For Doubtful Accounts Receivable,Gross Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,Cash Equivalents,Cash Financial
0,2026-06-30,7.428435e+09,7.428435e+09,1.935900e+10,5.682600e+10,3.041270e+11,4.826810e+11,3.888500e+10,3.041270e+11,1.653200e+10,...,NaN,8.087600e+10,8.087600e+10,-1.040000e+09,8.191600e+10,7.665100e+10,5.571600e+10,2.093500e+10,7.876000e+09,1.305900e+10
1,2025-06-30,7.434159e+09,7.434159e+09,1.290900e+10,6.058800e+10,2.013660e+11,3.866300e+11,4.991300e+10,2.013660e+11,1.743700e+10,...,NaN,6.990500e+10,6.990500e+10,-9.440000e+08,7.084900e+10,9.455500e+10,6.431300e+10,3.024200e+10,1.853100e+10,1.171100e+10
2,2024-06-30,7.434139e+09,7.434139e+09,3.331500e+10,6.712700e+10,1.216600e+11,3.201070e+11,3.444800e+10,1.216600e+11,1.549700e+10,...,3.940000e+08,5.692400e+10,5.692400e+10,-8.300000e+08,5.775400e+10,7.553100e+10,5.721600e+10,1.831500e+10,6.744000e+09,1.157100e+10
3,2023-06-30,7.432000e+09,7.432000e+09,1.253300e+10,5.996500e+10,1.289710e+11,2.534600e+11,8.010800e+10,1.289710e+11,1.272800e+10,...,7.090000e+08,4.868800e+10,4.868800e+10,-6.500000e+08,4.933800e+10,1.112560e+11,7.655200e+10,3.470400e+10,2.622600e+10,8.478000e+09
4,2022-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.144000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
balance_yearly = balance_yearly[balance_yearly["Date"].dt.year!= 2022]
balance_yearly

,Date,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Capital Lease Obligations,...,Raw Materials,Receivables,Accounts Receivable,Allowance For Doubtful Accounts Receivable,Gross Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,Cash Equivalents,Cash Financial
0,2026-06-30,7.428435e+09,7.428435e+09,1.935900e+10,5.682600e+10,3.041270e+11,4.826810e+11,3.888500e+10,3.041270e+11,1.653200e+10,...,NaN,8.087600e+10,8.087600e+10,-1.040000e+09,8.191600e+10,7.665100e+10,5.571600e+10,2.093500e+10,7.876000e+09,1.305900e+10
1,2025-06-30,7.434159e+09,7.434159e+09,1.290900e+10,6.058800e+10,2.013660e+11,3.866300e+11,4.991300e+10,2.013660e+11,1.743700e+10,...,NaN,6.990500e+10,6.990500e+10,-9.440000e+08,7.084900e+10,9.455500e+10,6.431300e+10,3.024200e+10,1.853100e+10,1.171100e+10
2,2024-06-30,7.434139e+09,7.434139e+09,3.331500e+10,6.712700e+10,1.216600e+11,3.201070e+11,3.444800e+10,1.216600e+11,1.549700e+10,...,394000000.0,5.692400e+10,5.692400e+10,-8.300000e+08,5.775400e+10,7.553100e+10,5.721600e+10,1.831500e+10,6.744000e+09,1.157100e+10
3,2023-06-30,7.432000e+09,7.432000e+09,1.253300e+10,5.996500e+10,1.289710e+11,2.534600e+11,8.010800e+10,1.289710e+11,1.272800e+10,...,709000000.0,4.868800e+10,4.868800e+10,-6.500000e+08,4.933800e+10,1.112560e+11,7.655200e+10,3.470400e+10,2.622600e+10,8.478000e+09

### Cash Flow Dataset

In [74]:
cashflow = cash_flow.copy()
cashflow = cashflow.drop(columns = pd.Timestamp("2022-06-30"))
cashflow_yearly = cashflow.T.reset_index()
cashflow_yearly.rename(columns = {"index":"Date"}, inplace= True)
cashflow_yearly["Date"] = pd.to_datetime(cashflow_yearly["Date"])

In [75]:
cashflow_yearly

,Date,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Issuance Of Capital Stock,Capital Expenditure,End Cash Position,Beginning Cash Position,Effect Of Exchange Rate Changes,...,Unrealized Gain Loss On Investment Securities,Asset Impairment Charge,Deferred Tax,Deferred Income Tax,Depreciation Amortization Depletion,Depreciation And Amortization,Depreciation,Operating Gains Losses,Gain Loss On Investment Securities,Net Income From Continuing Operations
0,2026-06-30,6.698700e+10,-2.227100e+10,-3.000000e+09,0.000000e+00,2.009000e+09,-1.159480e+11,2.093500e+10,3.024200e+10,-196000000.0,...,NaN,NaN,1.418900e+10,1.418900e+10,3.853400e+10,3.853400e+10,3.853400e+10,-1.104700e+10,NaN,1.337490e+11
1,2025-06-30,7.161100e+10,-1.842000e+10,-3.216000e+09,0.000000e+00,2.056000e+09,-6.455100e+10,3.024200e+10,1.831500e+10,63000000.0,...,-536000000.0,943000000.0,-7.056000e+09,-7.056000e+09,2.943300e+10,2.943300e+10,2.943300e+10,5.329000e+09,202000000.0,1.018320e+11
2,2024-06-30,7.407100e+10,-1.725400e+10,-2.907000e+10,2.439500e+10,2.002000e+09,-4.447700e+10,1.831500e+10,3.470400e+10,-210000000.0,...,-146000000.0,206000000.0,-4.738000e+09,-4.738000e+09,2.095800e+10,2.095800e+10,2.095800e+10,1.634000e+09,245000000.0,8.813600e+10
3,2023-06-30,5.947500e+10,-2.224500e+10,-2.750000e+09,0.000000e+00,1.866000e+09,-2.810700e+10,3.470400e+10,1.393100e+10,-194000000.0,...,-303000000.0,30000000.0,-6.059000e+09,-6.059000e+09,1.386100e+10,1.386100e+10,1.386100e+10,4.690000e+08,469000000.0,7.236100e+10

### Income dataset key values

In [76]:
income_yearly = income_yearly.sort_values("Date").reset_index(drop = True)
income_yearly["Revenue Growth %"]= income_yearly["Total Revenue"].pct_change()*100

In [77]:
income_yearly["Net Income Growth %"] = round(income_yearly["Net Income"].pct_change()*100,2)
income_yearly["Gross Margin %"] =round(income_yearly["Gross Profit"]/income_yearly["Total Revenue"]*100,2)
income_yearly["Operating Margin %"] = round(income_yearly["Operating Income"]/income_yearly["Total Revenue"]*100,2)
income_yearly[["Date","Total Revenue","Revenue Growth %","Gross Profit","Gross Margin %",
               "Net Income","Net Income Growth %","Operating Income","Operating Margin %"]]

,Date,Total Revenue,Revenue Growth %,Gross Profit,Gross Margin %,Net Income,Net Income Growth %,Operating Income,Operating Margin %
0,2023-06-30,2.119150e+11,NaN,1.460520e+11,68.92,7.236100e+10,NaN,8.852300e+10,41.77
1,2024-06-30,2.451220e+11,15.669962,1.710080e+11,69.76,8.813600e+10,21.80,1.094330e+11,44.64
2,2025-06-30,2.817240e+11,14.932156,1.938930e+11,68.82,1.018320e+11,15.54,1.285280e+11,45.62
3,2026-06-30,3.318390e+11,17.788687,2.254650e+11,67.94,1.337490e+11,31.34,1.552370e+11,46.78

In [78]:
income_yearly["Net Margin %"] = round(income_yearly["Net Income"]/income_yearly["Total Revenue"]*100,2)
income_yearly[["Date","Total Revenue","Net Income","Net Margin %"]]

        Date  Total Revenue    Net Income  Net Margin %
0 2023-06-30   2.119150e+11  7.236100e+10         34.15
1 2024-06-30   2.451220e+11  8.813600e+10         35.96
2 2025-06-30   2.817240e+11  1.018320e+11         36.15
3 2026-06-30   3.318390e+11  1.337490e+11         40.31

In [79]:
# EPS - Earnings Per Share
[c for c in income_yearly.columns if "EPS" in c]

['Diluted EPS', 'Basic EPS']

In [80]:
income_yearly["EPS Growth %"] = round(income_yearly["Diluted EPS"].pct_change()*100,2)
income_yearly[["Date","Total Revenue","Revenue Growth %","Gross Profit",
                                "Gross Margin %","Operating Income","Operating Margin %",
                                "Net Income","Net Margin %","Diluted EPS","EPS Growth %"]]

,Date,Total Revenue,Revenue Growth %,Gross Profit,Gross Margin %,Operating Income,Operating Margin %,Net Income,Net Margin %,Diluted EPS,EPS Growth %
0,2023-06-30,2.119150e+11,NaN,1.460520e+11,68.92,8.852300e+10,41.77,7.236100e+10,34.15,9.68,NaN
1,2024-06-30,2.451220e+11,15.669962,1.710080e+11,69.76,1.094330e+11,44.64,8.813600e+10,35.96,11.80,21.90
2,2025-06-30,2.817240e+11,14.932156,1.938930e+11,68.82,1.285280e+11,45.62,1.018320e+11,36.15,13.64,15.59
3,2026-06-30,3.318390e+11,17.788687,2.254650e+11,67.94,1.552370e+11,46.78,1.337490e+11,40.31,17.95,31.60

Balance sheet dataset key values

In [81]:
balance_yearly = balance_yearly.sort_values("Date").reset_index(drop = True)
balance_yearly[["Date","Total Assets","Total Liabilities Net Minority Interest"]]

        Date  Total Assets  Total Liabilities Net Minority Interest
0 2023-06-30  4.119760e+11                             2.057530e+11
1 2024-06-30  5.121630e+11                             2.436860e+11
2 2025-06-30  6.190030e+11                             2.755240e+11
3 2026-06-30  7.583760e+11                             3.159890e+11

In [82]:
[c for c in balance_yearly.columns if "Debt" in c or "Equity" in c]

['Net Debt',
 'Total Debt',
 'Common Stock Equity',
 'Total Equity Gross Minority Interest',
 'Stockholders Equity',
 'Other Equity Adjustments',
 'Long Term Debt And Capital Lease Obligation',
 'Long Term Debt',
 'Current Debt And Capital Lease Obligation',
 'Current Debt',
 'Long Term Equity Investment']

In [83]:
[c for c in balance_yearly.columns if "Assets" in c or "Liab" in c]

['Net Tangible Assets',
 'Total Liabilities Net Minority Interest',
 'Total Non Current Liabilities Net Minority Interest',
 'Other Non Current Liabilities',
 'Non Current Deferred Liabilities',
 'Non Current Deferred Taxes Liabilities',
 'Current Liabilities',
 'Other Current Liabilities',
 'Current Deferred Liabilities',
 'Total Assets',
 'Total Non Current Assets',
 'Other Non Current Assets',
 'Financial Assets',
 'Investmentin Financial Assets',
 'Financial Assets Designatedas Fair Value Through Profitor Loss Total',
 'Goodwill And Other Intangible Assets',
 'Other Intangible Assets',
 'Current Assets',
 'Other Current Assets',
 'Hedging Assets Current']

In [84]:
balance_yearly[["Date","Cash And Cash Equivalents","Total Debt","Stockholders Equity"]]

        Date  Cash And Cash Equivalents    Total Debt  Stockholders Equity
0 2023-06-30               3.470400e+10  5.996500e+10         2.062230e+11
1 2024-06-30               1.831500e+10  6.712700e+10         2.684770e+11
2 2025-06-30               3.024200e+10  6.058800e+10         3.434790e+11
3 2026-06-30               2.093500e+10  5.682600e+10         4.423870e+11

In [85]:
balance_yearly["Debt-to-Equity"] = round(balance_yearly["Total Debt"] /balance_yearly["Stockholders Equity"],2)

balance_yearly["Current Ratio"] = round(balance_yearly["Current Assets"] / balance_yearly["Current Liabilities"],2)

balance_yearly["ROE %"] = round(income_yearly["Net Income"].values /balance_yearly["Stockholders Equity"] * 100,2)
balance_yearly["ROA %"] = round(income_yearly["Net Income"].values/balance_yearly["Total Assets"]*100,2)
balance_yearly[["Date","Debt-to-Equity","Current Ratio","ROE %"]]

        Date  Debt-to-Equity  Current Ratio  ROE %
0 2023-06-30            0.29           1.77  35.09
1 2024-06-30            0.25           1.27  32.83
2 2025-06-30            0.18           1.35  29.65
3 2026-06-30            0.13           1.23  30.23

In [86]:
balance_yearly[["Date","Total Assets","Total Liabilities Net Minority Interest",
                                  "Cash And Cash Equivalents","Total Debt","Stockholders Equity",
                                  "Debt-to-Equity","Current Ratio","ROE %","ROA %"]]

,Date,Total Assets,Total Liabilities Net Minority Interest,Cash And Cash Equivalents,Total Debt,Stockholders Equity,Debt-to-Equity,Current Ratio,ROE %,ROA %
0,2023-06-30,4.119760e+11,2.057530e+11,3.470400e+10,5.996500e+10,2.062230e+11,0.29,1.77,35.09,17.56
1,2024-06-30,5.121630e+11,2.436860e+11,1.831500e+10,6.712700e+10,2.684770e+11,0.25,1.27,32.83,17.21
2,2025-06-30,6.190030e+11,2.755240e+11,3.024200e+10,6.058800e+10,3.434790e+11,0.18,1.35,29.65,16.45
3,2026-06-30,7.583760e+11,3.159890e+11,2.093500e+10,5.682600e+10,4.423870e+11,0.13,1.23,30.23,17.64

### Cash Flow Dataset key values

In [87]:
[c for c in cashflow_yearly.columns if "Cash" in c or "Capital" in c or "Free" in c]

['Free Cash Flow',
 'Repurchase Of Capital Stock',
 'Issuance Of Capital Stock',
 'Capital Expenditure',
 'End Cash Position',
 'Beginning Cash Position',
 'Changes In Cash',
 'Financing Cash Flow',
 'Cash Flow From Continuing Financing Activities',
 'Cash Dividends Paid',
 'Investing Cash Flow',
 'Cash Flow From Continuing Investing Activities',
 'Operating Cash Flow',
 'Cash Flow From Continuing Operating Activities',
 'Change In Working Capital',
 'Change In Other Working Capital']

In [88]:
cashflow_summary = cashflow_yearly[["Date","Operating Cash Flow","Capital Expenditure","Free Cash Flow"]]
cashflow_summary

        Date  Operating Cash Flow  Capital Expenditure  Free Cash Flow
0 2026-06-30         1.829350e+11        -1.159480e+11    6.698700e+10
1 2025-06-30         1.361620e+11        -6.455100e+10    7.161100e+10
2 2024-06-30         1.185480e+11        -4.447700e+10    7.407100e+10
3 2023-06-30         8.758200e+10        -2.810700e+10    5.947500e+10

In [89]:
cf = cashflow_yearly.sort_values("Date").merge(income_yearly[["Date","Total Revenue"]], on="Date")
cf["FCF Margin %"]     = round(cf["Free Cash Flow"] / cf["Total Revenue"] * 100,2)
cf["Capex % of OCF"]   = round(-cf["Capital Expenditure"] / cf["Operating Cash Flow"] * 100,2)
cf["FCF Growth %"]     = round(cf["Free Cash Flow"].pct_change() * 100,2)
cf["Shareholder Returns"] = round(-(cf["Repurchase Of Capital Stock"] + cf["Cash Dividends Paid"]),2)
cf["Returns % of FCF"] = round(cf["Shareholder Returns"] / cf["Free Cash Flow"] * 100,2)
cf

,Date,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Issuance Of Capital Stock,Capital Expenditure,End Cash Position,Beginning Cash Position,Effect Of Exchange Rate Changes,...,Depreciation,Operating Gains Losses,Gain Loss On Investment Securities,Net Income From Continuing Operations,Total Revenue,FCF Margin %,Capex % of OCF,FCF Growth %,Shareholder Returns,Returns % of FCF
0,2023-06-30,5.947500e+10,-2.224500e+10,-2.750000e+09,0.000000e+00,1.866000e+09,-2.810700e+10,3.470400e+10,1.393100e+10,-194000000.0,...,1.386100e+10,4.690000e+08,469000000.0,7.236100e+10,2.119150e+11,28.07,32.09,NaN,4.204500e+10,70.69
1,2024-06-30,7.407100e+10,-1.725400e+10,-2.907000e+10,2.439500e+10,2.002000e+09,-4.447700e+10,1.831500e+10,3.470400e+10,-210000000.0,...,2.095800e+10,1.634000e+09,245000000.0,8.813600e+10,2.451220e+11,30.22,37.52,24.54,3.902500e+10,52.69
2,2025-06-30,7.161100e+10,-1.842000e+10,-3.216000e+09,0.000000e+00,2.056000e+09,-6.455100e+10,3.024200e+10,1.831500e+10,63000000.0,...,2.943300e+10,5.329000e+09,202000000.0,1.018320e+11,2.817240e+11,25.42,47.41,-3.32,4.250200e+10,59.35
3,2026-06-30,6.698700e+10,-2.227100e+10,-3.000000e+09,0.000000e+00,2.009000e+09,-1.159480e+11,2.093500e+10,3.024200e+10,-196000000.0,...,3.853400e+10,-1.104700e+10,NaN,1.337490e+11,3.318390e+11,20.19,63.38,-6.46,4.871600e+10,72.72

### Historical Dataset key value

In [90]:
# Last 252 trading days - Trading days in 1 year
last_52_weeks = historical_data.tail(252)

# Last 52 week high
week_52_high = (last_52_weeks["High"].max())

# Last 52 week low
week_52_low = (last_52_weeks["Low"].min())

one_year_return = ((historical_data['Close'].iloc[-1]/historical_data['Close'].iloc[-252]-1)*100)

print("52-Week High:",week_52_high)
print("52-Week Low:",week_52_low)
print("One Year Return:",one_year_return)

52-Week High: 549.2013167264516
52-Week Low: 348.54386902384044
One Year Return: 0.39247421258938875

In [91]:
three_year_return = (historical_data['Close'].iloc[-1]/historical_data['Close'].iloc[-756]-1)*100
print("Three Year Return:",three_year_return)

Three Year Return: 67.68573609934583

In [92]:
five_year_date = historical_data.index.min()
five_year_date

Timestamp('2021-10-11 00:00:00-0400', tz='America/New_York')

In [93]:
five_year_price = historical_data.loc[historical_data.index>=five_year_date,"Close"].iloc[0]
five_year_return = (historical_data['Close'].iloc[-1]/five_year_price-1)*100
print("Five Year Return:",five_year_return)

Five Year Return: 85.07291706180678

In [94]:
historical_data["Daily Return"] = historical_data["Close"].pct_change()
annual_volatility = round(historical_data["Daily Return"].std()* (252 ** 0.5)* 100,2)
print("Annualized Volatility:", annual_volatility)

Annualized Volatility: 28.18

In [95]:
historical_data["Peak"] = historical_data["Close"].cummax() #Cumulative Maximum

In [96]:
historical_data["Drawdown"] = (historical_data["Close"]-historical_data["Peak"])/historical_data["Peak"]
historical_data[["Close","Peak","Drawdown"]]

                                Close        Peak  Drawdown
Date
2021-10-11 00:00:00-04:00  282.380585  282.380585  0.000000
2021-10-12 00:00:00-04:00  281.084900  282.380585 -0.004588
2021-10-13 00:00:00-04:00  284.376801  284.376801  0.000000
2021-10-14 00:00:00-04:00  290.557465  290.557465  0.000000
2021-10-15 00:00:00-04:00  291.958618  291.958618  0.000000
...                               ...         ...       ...
2026-10-02 00:00:00-04:00  517.530029  537.646423 -0.037416
2026-10-05 00:00:00-04:00  525.179993  537.646423 -0.023187
2026-10-06 00:00:00-04:00  529.299988  537.646423 -0.015524
2026-10-07 00:00:00-04:00  529.760010  537.646423 -0.014668
2026-10-08 00:00:00-04:00  522.609985  537.646423 -0.027967

[1254 rows x 3 columns]

In [97]:
max_drawdown = (historical_data["Drawdown"].min())
max_drawdown_percentage = max_drawdown *100
max_drawdown_percentage

-37.14847417400641

In [98]:
initial_price = five_year_price
final_price = historical_data['Close'].iloc[-1] #last row
annualized_return = (final_price/initial_price)**(1/5)-1
annualized_return_percentage = annualized_return*100
print("Annualized Return Percentage:",annualized_return_percentage)

Annualized Return Percentage: 13.101554503343294

In [99]:
sharpe_ratio = (annualized_return-0)/annual_volatility *100
print("Sharpe ratio:",sharpe_ratio)

Sharpe ratio: 0.46492386456150797

# Metric for Historical Values

In [100]:
hs = pd.DataFrame({
    "Metric": ["Initial Price","Latest Price","52-Week High","52-Week Low","1-Year Return %",
               "3-Year Return %","5-Year Return %","Annualized Volatility %","Sharpe Ratio","Maximum Drawdown %","Annualized Return Percentage"],
    "Value": [initial_price,final_price,week_52_high,week_52_low,one_year_return,
              three_year_return,five_year_return,annual_volatility,sharpe_ratio,max_drawdown_percentage,annualized_return_percentage]})
hs

                          Metric       Value
0                  Initial Price  282.380585
1                   Latest Price  522.609985
2                   52-Week High  549.201317
3                    52-Week Low  348.543869
4                1-Year Return %    0.392474
5                3-Year Return %   67.685736
6                5-Year Return %   85.072917
7        Annualized Volatility %   28.180000
8                   Sharpe Ratio    0.464924
9             Maximum Drawdown %  -37.148474
10  Annualized Return Percentage   13.101555

# Summary metrics for income statement, balance sheet and cash flow

In [101]:
income_yearly = income_yearly.set_index("Date")
balance_yearly = balance_yearly.set_index("Date")
cf = cf.set_index("Date")

In [102]:
yrs = income_yearly.index                                       # fiscal year-end dates, oldest -> newest

m = pd.DataFrame(index=yrs)
m["Revenue"]          = income_yearly["Total Revenue"]
m["Gross Profit"]     = income_yearly["Gross Profit"]
m["Operating Income"] = income_yearly["Operating Income"]
m["Net Income"]       = income_yearly["Net Income"]
m["Diluted EPS"]      = income_yearly["Diluted EPS"]
m["Revenue Growth %"]    = income_yearly["Revenue Growth %"]
m["Net Income Growth %"] = income_yearly["Net Income Growth %"]
m["EPS Growth %"]        = income_yearly["EPS Growth %"]
m["Gross Margin %"]     = income_yearly["Gross Margin %"]
m["Operating Margin %"] = income_yearly["Operating Margin %"]
m["Net Margin %"]       = income_yearly["Net Margin %"]

m["Total Assets"]       = balance_yearly["Total Assets"]
m["Total Liabilities"]  = balance_yearly["Total Liabilities Net Minority Interest"]
m["Equity"]             = balance_yearly["Stockholders Equity"]
m["Total Debt"]         = balance_yearly["Total Debt"]
m["Net Debt"]           = balance_yearly["Net Debt"]                    # as defined by Yahoo Finance
m["Cash & Equivalents"] = balance_yearly["Cash And Cash Equivalents"]
m["Cash + ST Investments"] = balance_yearly["Cash Cash Equivalents And Short Term Investments"]
m["Current Assets"]     = balance_yearly["Current Assets"]
m["Current Liabilities"] = balance_yearly["Current Liabilities"]
m["Current Ratio"]      = balance_yearly["Current Ratio"]
m["Debt to Equity"]     = balance_yearly["Debt-to-Equity"]
m["ROE %"]              = balance_yearly["ROE %"]
m["ROA %"]              = balance_yearly["ROA %"]
m["Operating Cash Flow"] = cf["Operating Cash Flow"]
m["Capex"]               = cf["Capital Expenditure"]             # negative = cash outflow
m["FCF (reported)"]      = cf["Free Cash Flow"]
m["FCF (computed)"]      = m["Operating Cash Flow"] + m["Capex"]
m["FCF Margin %"]        = cf["FCF Margin %"]
m["Capex % of OCF"]      = cf["Capex % of OCF"]
m["Buybacks"]            = cf["Repurchase Of Capital Stock"]
m["Dividends Paid"]      = cf["Cash Dividends Paid"]
m["Shareholder Returns"] = cf["Shareholder Returns"]
m["Returns % of FCF"]    = cf["Returns % of FCF"]

m

,Revenue,Gross Profit,Operating Income,Net Income,Diluted EPS,Revenue Growth %,Net Income Growth %,EPS Growth %,Gross Margin %,Operating Margin %,...,Operating Cash Flow,Capex,FCF (reported),FCF (computed),FCF Margin %,Capex % of OCF,Buybacks,Dividends Paid,Shareholder Returns,Returns % of FCF
Date,,,,,,,,,,,,,,,,,,,,,
2023-06-30,2.119150e+11,1.460520e+11,8.852300e+10,7.236100e+10,9.68,NaN,NaN,NaN,68.92,41.77,...,8.758200e+10,-2.810700e+10,5.947500e+10,5.947500e+10,28.07,32.09,-2.224500e+10,-1.980000e+10,4.204500e+10,70.69
2024-06-30,2.451220e+11,1.710080e+11,1.094330e+11,8.813600e+10,11.80,15.669962,21.80,21.90,69.76,44.64,...,1.185480e+11,-4.447700e+10,7.407100e+10,7.407100e+10,30.22,37.52,-1.725400e+10,-2.177100e+10,3.902500e+10,52.69
2025-06-30,2.817240e+11,1.938930e+11,1.285280e+11,1.018320e+11,13.64,14.932156,15.54,15.59,68.82,45.62,...,1.361620e+11,-6.455100e+10,7.161100e+10,7.161100e+10,25.42,47.41,-1.842000e+10,-2.408200e+10,4.250200e+10,59.35
2026-06-30,3.318390e+11,2.254650e+11,1.552370e+11,1.337490e+11,17.95,17.788687,31.34,31.60,67.94,46.78,...,1.829350e+11,-1.159480e+11,6.698700e+10,6.698700e+10,20.19,63.38,-2.227100e+10,-2.644500e+10,4.871600e+10,72.72

#  Generate Embeddings  - chunks to vectors

In [ ]:
!pip install faiss-cpu
!pip install -U langchain-text-splitters

In [ ]:
import numpy as np
import faiss                # vector store
from google import genai     # communication with gemini api
from google.genai import types
from sentence_transformers import SentenceTransformer  # sentence embedding
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [ ]:
company_info = ticker.info
company_info

In [ ]:
TICKER  = "MSFT"
COMPANY = "Microsoft Corporation"

from google.colab import userdata
api_key = userdata.get("GOOGLE_API_NAME")
print(api_key is not None)

client = genai.Client(api_key = api_key)

In [ ]:
documents = []
def add_doc(header, source, text):
    if isinstance(text, (list, tuple)):
        text = " ".join(text)
    documents.append({"header": header, "source": source, "text": text})

SRC_IS, SRC_BS, SRC_CF = "Yahoo Finance annual income statement", "Yahoo Finance annual balance sheet", "Yahoo Finance annual cash flow statement"
SRC_PX, SRC_INFO, SRC_CALC = "Yahoo Finance daily price history", "Yahoo Finance company info", "Calculated in Python from the Yahoo Finance statements"

In [ ]:
def usd(x):
    if pd.isna(x): return "not reported"
    s = "-" if x < 0 else ""
    return f"{s}${abs(x)/1e9:,.2f}B"

In [ ]:


m_valid = m.dropna(subset=["Revenue"])      # skip empty year colum
for date, r in m_valid.iterrows():
    add_doc(f"Income statement", SRC_IS, [
        f"{COMPANY} income statement.",
        f"Total revenue: {usd(r['Revenue'])} (growth vs prior year: {(r['Revenue Growth %'])}).",
        f"Gross profit: {usd(r['Gross Profit'])}; gross margin: {(r['Gross Margin %'])}.",
        f"Operating income: {usd(r['Operating Income'])}; operating margin: {(r['Operating Margin %'])}.",
        f"Net income: {usd(r['Net Income'])} (growth: {(r['Net Income Growth %'])}); net margin: {(r['Net Margin %'])}.",
        f"Diluted EPS: {(r['Diluted EPS'])} (growth: {(r['EPS Growth %'])})."])

    add_doc(f"Balance sheet", SRC_BS, [
        f"{COMPANY} .",
        f"Total assets: {usd(r['Total Assets'])}; total liabilities: {usd(r['Total Liabilities'])}; stockholders' equity: {usd(r['Equity'])}.",
        f"Total debt: {usd(r['Total Debt'])}; net debt (as defined by Yahoo Finance): {usd(r['Net Debt'])}.",
        f"Cash and cash equivalents: {usd(r['Cash & Equivalents'])}; cash plus short-term investments: {usd(r['Cash + ST Investments'])}.",
        f"Current assets: {usd(r['Current Assets'])}; current liabilities: {usd(r['Current Liabilities'])}; current ratio: {(r['Current Ratio'])}.",
        f"Debt to equity: {(r['Debt to Equity'])}."])

    add_doc(f"Cash flow", SRC_CF, [
        f"{COMPANY} - cash flow statement.",
        f"Operating cash flow: {usd(r['Operating Cash Flow'])}; capital expenditure: {usd(r['Capex'])} (cash outflow).",
        f"Free cash flow (reported by Yahoo Finance): {usd(r['FCF (reported)'])}; free cash flow margin: {(r['FCF Margin %'])}.",
        f"Capital expenditure as a share of operating cash flow: {(r['Capex % of OCF'])}.",
        f"Share buybacks: {usd(abs(r['Buybacks']) if pd.notna(r['Buybacks']) else np.nan)}; dividends paid: {usd(abs(r['Dividends Paid']) if pd.notna(r['Dividends Paid']) else np.nan)}.",
        f"Total returned to shareholders (buybacks plus dividends): {usd(r['Shareholder Returns'])}, equal to {(r['Returns % of FCF'])} of free cash flow."])

    add_doc(f"Financial ratios", SRC_CALC, [
        f"{COMPANY}  financial ratios.",
        f"Gross margin {(r['Gross Margin %'])}; operating margin {(r['Operating Margin %'])}; net margin {(r['Net Margin %'])}; free cash flow margin {(r['FCF Margin %'])}.",
        f"Return on equity {(r['ROE %'])}; return on assets {(r['ROA %'])} (year-end balances).",
        f"Current ratio {(r['Current Ratio'])}; debt to equity {(r['Debt to Equity'])}."])

print(len(documents), "documents so far")

In [111]:
info = ticker.info
g = lambda k: info.get(k)

add_doc("Company profile", SRC_INFO, [
    f"Company: {g('longName') or COMPANY}; ticker {TICKER}.",
    f"Sector: {g('sector')}; industry: {g('industry')}; country: {g('country') or 'not available'}.",
    f"Summary:{g('longBusinessSummary')}."])

px = dict(zip(hs["Metric"], hs["Value"]))
d0, d1 = historical_data.index[0].date(), historical_data.index[-1].date()
add_doc("Stock price performance", SRC_PX, [
    f"Price history covers {d0} to {d1}. Initial close ${px['Initial Price']:,.2f}; latest close ${px['Latest Price']:,.2f}.",
    f"52-week high ${px['52-Week High']:,.2f}; 52-week low ${px['52-Week Low']:,.2f}.",
    f"Returns: 1-year {(px['1-Year Return %'])}; 3-year {(px['3-Year Return %'])}; 5-year {(px['5-Year Return %'])}; annualized return {(px['Annualized Return Percentage'])}."])

add_doc("Stock risk metrics", SRC_PX, [
    f"Annualized volatility: {(px['Annualized Volatility %'])}.",
    f"Maximum drawdown over the period: {(px['Maximum Drawdown %'])}.",
    f"Sharpe ratio (assuming a 0% risk-free rate): {(px['Sharpe Ratio'])}."])

add_doc("Data not available in this knowledge base", SRC_CALC, [
    "This knowledge base contains only: annual income statement, balance sheet and cash flow figures, "
    "ratios calculated from them, a company profile, a valuation snapshot and 5 years of price history.",
    "It does NOT contain: revenue by segment or product, management guidance, analyst forecasts or price targets, "
    "news, competitor data, quarterly results, or any information after the download date."])

print(len(documents), "documents in the knowledge base")
for chunks in documents: print(chunks["header"])

24 documents in the knowledge base
Income statement
Balance sheet
Cash flow
Financial ratios
Income statement
Balance sheet
Cash flow
Financial ratios
Income statement
Balance sheet
Cash flow
Financial ratios
Income statement
Balance sheet
Cash flow
Financial ratios
Company profile
Stock price performance
Stock risk metrics
Data not available in this knowledge base
Company profile
Stock price performance
Stock risk metrics
Data not available in this knowledge base

### Embedding and storing vectors in FAISS

In [126]:
EMBED_MODEL = "gemini-embedding-001"
GEN_MODEL   = "gemini-3.5-flash"

EMBED_DIM = 768

def embed(texts, task_type):
    out = []
    for i in range(0, len(texts), 50):
            res = client.models.embed_content(
                model=EMBED_MODEL, contents=texts[i:i+50],
                config=types.EmbedContentConfig(task_type=task_type, output_dimensionality=EMBED_DIM))
            out.extend([e.values for e in res.embeddings])
    return np.array(out,dtype = "float32")

chunk_texts = [f"{chunks['header']}. {chunks['text']}" for chunks in documents]
chunk_vecs  = embed(chunk_texts, "RETRIEVAL_DOCUMENT")
# Add index
index = faiss.IndexFlatIP(EMBED_DIM)
index.add(chunk_vecs)
print("Vectors in FAISS index:", index.ntotal)

Vectors in FAISS index: 24

# Retrieve relevent chunks and answers

In [129]:
def retrieve(question, k=2):
    q = embed([question], "RETRIEVAL_QUERY")
    scores, ids = index.search(q, k)
    return [(documents[int(i)], float(s))
           for i, s in zip(ids[0], scores[0]) if 0<=i<len(documents)]

def ask(question, k=2, show_context=False):
    hits = retrieve(question, k)
    # answer for the question
    context = "\n\n".join(f"[{n}] {chunk['header']} (source: {chunk['source']})\n{chunk['text']}"
                          for n, (chunk, source) in enumerate(hits, 1))
    # prompt build
    prompt = f"CONTEXT:\n{context}\n\nQUESTION: {question}"
    #generate ans
    resp = client.models.generate_content(
        model=GEN_MODEL, contents=prompt)
    print("Question:", question)
    print("Retrieved:", [(chunk["header"], round(source, 3)) for chunk, source in hits])
    if show_context: print(context)
    print("\n" + resp.text + "\n" + "=" * 80)
    return resp.text

In [131]:
test_questions = [
    "1.How has Microsoft's revenue and revenue growth changed over the years?",
    "2.Is Microsoft profitable? Discuss net income, margins and EPS.",
    "3.How strong is Microsoft's balance sheet? Discuss assets, liabilities, debt and cash.",
    "4.How much free cash flow does Microsoft generate and how much is returned to shareholders?",
    "5.What are the key financial ratios and what do they say about the company?",
    "6.How has the stock performed historically and how risky is it?",
    "7.Summarise Microsoft's key financial strengths and risks.",
]
for q in test_questions:
  ask(q)

Question: 1.How has Microsoft's revenue and revenue growth changed over the years?
Retrieved: [('Income statement', 0.245), ('Income statement', 0.245)]

Based on the provided income statement data, Microsoft's revenue and revenue growth changed as follows over the two periods (ordered chronologically from oldest to newest based on the growth calculation):

* **Prior Period (Context [2]):**
  * **Total Revenue:** $245.12 billion
  * **Revenue Growth:** 15.67% (15.66996201307127%) compared to the previous year.

* **Recent Period (Context [1]):**
  * **Total Revenue:** Increased to $281.72 billion.
  * **Revenue Growth:** Slowed down slightly to 14.93% (14.932156232406712%) compared to the prior year.

**Summary of changes:**
While Microsoft's absolute total revenue continued to grow (increasing by $36.6 billion), the year-over-year revenue growth rate decelerated slightly from 15.67% to 14.93%.
================================================================================
Question: 2.Is Microsoft profitable? Discuss net income, margins and EPS.
Retrieved: [('Income statement', 0.267), ('Income statement', 0.267)]

Based on the provided financial data, **yes, Microsoft is highly profitable** and has shown significant earnings growth.

Here is a detailed breakdown of its profitability based on net income, margins, and EPS:

### 1. Net Income
* **Prior Year:** Microsoft recorded a net income of **$72.36 billion**.
* **Recent Year:** Net income grew substantially to **$101.83 billion**.
* **Growth:** This represents a year-over-year net income growth of **15.54%**, demonstrating robust bottom-line expansion.

### 2. Margins
Microsoft maintains exceptionally high margins, reflecting its strong pricing power and operational efficiency:
* **Gross Margin:** Remained very stable, shifting slightly from **68.92%** in the prior year to **68.82%** in the recent year.
* **Operating Margin:** Improved from **41.77%** to **45.62%**, showing that the company became more efficient at managing its operating expenses as it scaled.
* **Net Margin:** Increased from **34.15%** to **36.15%**. This means that in the most recent year, Microsoft converted over 36% of its total revenue directly into net profit.

### 3. Earnings Per Share (EPS)
* **Prior Year Diluted EPS:** **$9.68**
* **Recent Year Diluted EPS:** **$13.64**
* **Growth:** Diluted EPS grew by **15.59%** year-over-year, indicating that profitability per share increased in line with the company’s overall net income growth.
================================================================================
Question: 3.How strong is Microsoft's balance sheet? Discuss assets, liabilities, debt and cash.
Retrieved: [('Balance sheet', 0.275), ('Balance sheet', 0.274)]

Based on the provided financial data, Microsoft’s balance sheet is exceptionally strong. A comparison of the two reporting periods (Context [1] and Context [2]) demonstrates massive asset growth, a substantial equity base, low leverage, and a healthy liquidity position.

Here is a detailed breakdown of Microsoft's balance sheet strength across the requested categories:

### 1. Assets
Microsoft’s asset base experienced massive growth between the two periods:
* **Total Assets:** Increased from **$411.98 billion** in Context [2] to **$758.38 billion** in Context [1].
* **Current Assets:** Grew from **$184.26 billion** in Context [2] to **$207.71 billion** in Context [1].
* **Implication:** The near-doubling of total assets indicates a highly capitalized company with a rapidly expanding base of resources.

### 2. Liabilities and Equity
While liabilities increased, they did not grow as quickly as assets or stockholders' equity:
* **Total Liabilities:** Rose from **$205.75 billion** in Context [2] to **$315.99 billion** in Context [1].
* **Current Liabilities:** Increased from **$104.15 billion** in Context [2] to **$168.82 billion** in Context [1].
* **Stockholders' Equity:** More than doubled, surging from **$206.22 billion** in Context [2] to **$442.39 billion** in Context [1].
* **Implication:** Because equity grew faster than liabilities, Microsoft's overall capital structure became even safer and more heavily funded by equity rather than debt.

### 3. Debt
Microsoft maintains an incredibly low-risk debt profile:
* **Total Debt:** Actually decreased from **$59.97 billion** in Context [2] to **$56.83 billion** in Context [1].
* **Debt-to-Equity Ratio:** Fell dramatically from a already-low **0.29** in Context [2] to an exceptionally strong **0.13** in Context [1].
* **Net Debt:** Rose slightly from **$12.53 billion** to **$19.36 billion**, but remains extremely low relative to the company's size.
* **Implication:** Microsoft has minimal dependency on debt, giving it immense financial flexibility and very low insolvency risk.

### 4. Cash and Liquidity
While total cash reserves and short-term liquidity ratios declined between the two periods, Microsoft's liquidity remains highly secure:
* **Cash and Cash Equivalents:** Decreased from **$34.70 billion** in Context [2] to **$20.93 billion** in Context [1].
* **Cash Plus Short-Term Investments:** Decreased from **$111.26 billion** in Context [2] to **$76.65 billion** in Context [1].
* **Current Ratio:** Decreased from **1.77** in Context [2] to **1.23** in Context [1].
* **Implication:** Even though liquidity tightened slightly (with a current ratio of 1.23, meaning current assets still comfortably exceed current liabilities), having over $76 billion in cash and short-term investments ensures Microsoft can easily cover its short-term obligations.
================================================================================
Question: 4.How much free cash flow does Microsoft generate and how much is returned to shareholders?
Retrieved: [('Cash flow', 0.282), ('Cash flow', 0.282)]

Based on the provided cash flow statements, the free cash flow Microsoft generates and the amount returned to shareholders are reported for two different periods:

* **According to Context [1]:**
  * **Free cash flow generated:** $74.07 billion
  * **Total returned to shareholders:** $39.02 billion (consisting of $17.25 billion in share buybacks and $21.77 billion in dividends, which is 52.69% of the free cash flow).

* **According to Context [2]:**
  * **Free cash flow generated:** $59.48 billion
  * **Total returned to shareholders:** $42.05 billion (consisting of $22.25 billion in share buybacks and $19.80 billion in dividends, which is 70.69% of the free cash flow).
================================================================================
Question: 5.What are the key financial ratios and what do they say about the company?
Retrieved: [('Financial ratios', 0.241), ('Financial ratios', 0.239)]

Based on the provided context, the key financial ratios for Microsoft Corporation are presented across two different datasets/periods:

*   **Gross Margin:** 68.82 in [1] and 69.76 in [2]
*   **Operating Margin:** 45.62 in [1] and 44.64 in [2]
*   **Net Margin:** 36.15 in [1] and 35.96 in [2]
*   **Free Cash Flow Margin:** 25.42 in [1] and 30.22 in [2]
*   **Return on Equity:** 29.65 in [1] and 32.83 in [2]
*   **Return on Assets (year-end balances):** 16.45 in [1] and 17.21 in [2]
*   **Current Ratio:** 1.35 in [1] and 1.27 in [2]
*   **Debt to Equity:** 0.18 in [1] and 0.25 in [2]

**What they say about the company:**
The provided text only contains these raw numerical calculations and does not include any qualitative analysis, interpretation, or explanation of what these ratios mean or indicate about the company's financial health, performance, or operations.
================================================================================
Question: 6.How has the stock performed historically and how risky is it?
Retrieved: [('Stock risk metrics', 0.259), ('Stock risk metrics', 0.258)]

Based on the historical daily price metrics provided from Yahoo Finance, the stock's risk and performance are characterized by the following:

### **Risk Profile**
* **Annualized Volatility:** **28.18**, indicating a relatively high level of price fluctuation.
* **Maximum Drawdown:** Approximately **-37.15%** (specifically between -37.14847298% and -37.14847417%). This represents the largest peak-to-trough decline the stock experienced over the analyzed period, highlighting significant downside risk.

### **Historical Performance (Risk-Adjusted)**
* **Sharpe Ratio:** Approximately **0.465** (specifically between 0.46492386 and 0.46492404), assuming a 0% risk-free rate.
  * *Interpretation:* A Sharpe ratio in this range indicates that the stock has delivered positive historical returns, but its risk-adjusted performance is relatively modest, yielding about 0.46 units of return for every unit of volatility/risk taken.
================================================================================
Question: 7.Summarise Microsoft's key financial strengths and risks.
Retrieved: [('Financial ratios', 0.248), ('Financial ratios', 0.248)]

Based on the provided financial ratios, here is a summary of Microsoft's key financial strengths and risks (represented by declining trends in the data):

### **Financial Strengths**
*   **High and Improving Profitability:**
    *   **Operating Margin** increased from 41.77% in [1] to 46.78% in [2].
    *   **Net Margin** increased from 34.15% in [1] to 40.31% in [2].
    *   **Gross Margin** remains consistently high in both periods (68.92% and 67.94%).
*   **Strong Return on Investment:** Return on Equity (ROE) is exceptionally high at 35.09% in [1] and 30.23% in [2]. Return on Assets (ROA) remains stable and strong at 17.56% in [1] and 17.64% in [2].
*   **Very Low Debt/Leverage:** The debt-to-equity ratio is low and further decreased from 0.29 in [1] to 0.13 in [2], indicating minimal reliance on debt.
*   **Healthy Liquidity:** The current ratio remains above 1.0 in both periods (1.77 and 1.23), meaning the company possesses sufficient short-term assets to cover its short-term liabilities.

### **Financial Risks & Declining Trends**
*   **Significant Drop in Free Cash Flow Margin:** The free cash flow margin decreased notably from 28.07% in [1] to 20.19% in [2].
*   **Reduced Liquidity Buffer:** The current ratio decreased from 1.77 to 1.23, indicating a reduction in short-term financial flexibility.
*   **Decline in Return on Equity:** ROE fell from 35.09% to 30.23% between the two periods.
*   **Slight Gross Margin Compression:** Gross margin experienced a slight decrease from 68.92% down to 67.94%.
================================================================================

ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.5-flash\nPlease retry in 11h1m25.360325235s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '39685s'}]}}